name: Build, Start Docker, Test Local

on:
  workflow_dispatch

jobs:
  k6_local_test:
    name: k6 nightly test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Docker Build and Start
        run: |
          docker build -t hello-app . 
          docker run -d -p 5000:5000 -it hello-app

      - name: download and extract k6 release binaries
        run: |
           wget https://github.com/grafana/k6/releases/download/v0.34.1/k6-v0.34.1-linux-amd64.tar.gz
           tar xvf k6-v0.34.1-linux-amd64.tar.gz  --strip-components 1
      - name: Install packages
        run: |
          npm install
      - name: run tests
        run: |
          ./k6 run local.js --out json=results.json --no-thresholds
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: results.json
          path: results.json
          retention-days: 5
