name: Run K6 from Kubernetes

on:
  workflow_dispatch

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: autopilot-cluster-1    # Add your cluster name here.
  GKE_ZONE: europe-west2   # Add your cluster zone here.
  DEPLOYMENT_NAME: hello-app # Add your deployment name here.
  IMAGE: hello-world

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |-
        gcloud --quiet auth configure-docker
    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}
        
  
    # remove stale resources
    - name: Clean UP 
      run: |-
        kubectl delete -f k6job.yml || true
        kubectl delete configmap test || true
        
    # Deploy the Docker image to the GKE cluster
    - name: Deploy and Wait
      run: |-
        kubectl create configmap test --from-file=remote.js
        kubectl apply -f k6job.yml 
        kubectl wait --for=condition=complete job/myjob
        
